name: Auto Update Stream
on:
  schedule:
    - cron: '*/34 * * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm install youtubei.js
      - run: node tarik.js
      - name: Commit & Push
        run: |
          git config user.name "Bot"
          git config user.email "bot@github.com"
          git add stream_links.json
          git commit -m "Update stream links" || exit 0
          git push
